name: Issue Bot

on:
  issues:
    types: [opened]
permissions:
  issues: write   
  contents: read
jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygithub

      - name: Run bot script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python - << 'EOF'
          from github import Github
          import os

          TOKEN = os.getenv("GITHUB_TOKEN")
          REPO_NAME = "AruzCandlr/MonnAboveTest"
          BOT_MESSAGE = "Monn Above ALL!!!!!!"

          g = Github(auth=Auth.Token(TOKEN))
          repo = g.get_repo(REPO_NAME)

          issues = repo.get_issues(state="open")
          for issue in issues:
              already_commented = any(
                  BOT_MESSAGE in comment.body for comment in issue.get_comments()
              )
              if not already_commented:
                  print(f"💬 Commenting on issue #{issue.number}")
                  issue.create_comment(BOT_MESSAGE)
          EOF
